// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urgovbawwkhfznorcxqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZ292YmF3d2toZnpub3JjeHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTI0OTUsImV4cCI6MjA1ODY2ODQ5NX0.sscnCc6kpw6OH2Uq6JM0pKA512yt1hDdRDrzqPUlHLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);